### ISSUE TITLE
Update python dependencies

### ISSUE THREAD

**Issue by Thalyum** [elebihan/yaprogen#1]
Build with python 3.5 fails

```
Installed /home/paul-erwan/.local/lib/python3.5/site-packages/yaprogen-0.6.0-py3.5.egg
Processing dependencies for yaprogen==0.6.0
Searching for pystache>=0.5
Reading https://pypi.org/simple/pystache/
Downloading https://files.pythonhosted.org/packages/3f/e7/8750ba6c6101d6aa5ceeb20c013adf2c6f3554a12c71d75654b468404bfa/pystache-0.6.0.tar.gz#sha256=93bf92b2149a4c4b58d12142e2c4c6dd5c08d89e4c95afccd4b6efe2ee1d470d
Best match: pystache 0.6.0
Processing pystache-0.6.0.tar.gz
Writing /tmp/easy_install-xo_kedbx/pystache-0.6.0/setup.cfg
Running pystache-0.6.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-xo_kedbx/pystache-0.6.0/egg-dist-tmp-99vpzzvu
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 44, in _execfile
    code = compile(script, filename, 'exec')
  File "/tmp/easy_install-xo_kedbx/pystache-0.6.0/setup.py", line 183
    command = f"pandoc -f markdown-smart --write=rst --output={rst_temp_path} {md_path}"
                                                                                       ^
SyntaxError: invalid syntax
```

The configuration requests pystache >= 0.5, so it installs the latest version available: 0.6, which uses f-strings. They appeared with python 3.6.
So either `yaprogen` requires python 3.6+, or `pystache` dependency must be updated (I think we can use pystache 0.5.4) to keep python3.6- support.

**Comment by Thalyum** [comment]
Missing dependency: `docutils`

```
Traceback (most recent call last):
  File "/home/paul-erwan/Projects/Tools/yaprogen/setup.py", line 23, in <module>
    from disthelpers import extract_messages, init_catalog, update_catalog
  File "/home/paul-erwan/Projects/Tools/yaprogen/disthelpers.py", line 29, in <module>
    from docutils.core import publish_file
ModuleNotFoundError: No module named 'docutils'
```

**Comment by Thalyum** [comment]
Also, I think the `pystache` minimal dependency to 0.5 must be updated.
According to [this release note](https://pypi.org/project/pystache/0.5.0/), `pystache 0.5` does not support python3. The support for python 3 was introduced by [0.5.1](https://pypi.org/project/pystache/0.5.1/)
